//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.09 at 10:44:27 AM MST 
//


package com.lo9ic.research.noaa.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="more-information" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="production-center" type="{}production-centerType" minOccurs="0"/>
 *         &lt;element name="disclaimer" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="credit-logo" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="feedback" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sourceType", propOrder = {

})
public class SourceType {

    @XmlElement(name = "more-information", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String moreInformation;
    @XmlElement(name = "production-center")
    protected ProductionCenterType productionCenter;
    @XmlSchemaType(name = "anyURI")
    protected String disclaimer;
    @XmlSchemaType(name = "anyURI")
    protected String credit;
    @XmlElement(name = "credit-logo")
    @XmlSchemaType(name = "anyURI")
    protected String creditLogo;
    @XmlSchemaType(name = "anyURI")
    protected String feedback;

    /**
     * Gets the value of the moreInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoreInformation() {
        return moreInformation;
    }

    /**
     * Sets the value of the moreInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoreInformation(String value) {
        this.moreInformation = value;
    }

    /**
     * Gets the value of the productionCenter property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionCenterType }
     *     
     */
    public ProductionCenterType getProductionCenter() {
        return productionCenter;
    }

    /**
     * Sets the value of the productionCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionCenterType }
     *     
     */
    public void setProductionCenter(ProductionCenterType value) {
        this.productionCenter = value;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclaimer() {
        return disclaimer;
    }

    /**
     * Sets the value of the disclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclaimer(String value) {
        this.disclaimer = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * Gets the value of the creditLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditLogo() {
        return creditLogo;
    }

    /**
     * Sets the value of the creditLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditLogo(String value) {
        this.creditLogo = value;
    }

    /**
     * Gets the value of the feedback property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * Sets the value of the feedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeedback(String value) {
        this.feedback = value;
    }

}
